#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : R-callr
Version  : 3.7.6
Release  : 78
URL      : https://cran.r-project.org/src/contrib/callr_3.7.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/callr_3.7.6.tar.gz
Summary  : Call R from R
Group    : Development/Tools
License  : MIT
Requires: R-R6
Requires: R-processx
BuildRequires : R-R6
BuildRequires : R-processx
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
R process, without affecting the current R process at all.  This
    packages does exactly that.

%prep
%setup -q -n callr
pushd ..
cp -a callr buildavx2
popd
pushd ..
cp -a callr buildavx512
popd
pushd ..
cp -a callr buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711374902

%install
export SOURCE_DATE_EPOCH=1711374902
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/callr/COPYRIGHTS
/usr/lib64/R/library/callr/DESCRIPTION
/usr/lib64/R/library/callr/INDEX
/usr/lib64/R/library/callr/LICENSE
/usr/lib64/R/library/callr/Meta/Rd.rds
/usr/lib64/R/library/callr/Meta/features.rds
/usr/lib64/R/library/callr/Meta/hsearch.rds
/usr/lib64/R/library/callr/Meta/links.rds
/usr/lib64/R/library/callr/Meta/nsInfo.rds
/usr/lib64/R/library/callr/Meta/package.rds
/usr/lib64/R/library/callr/NAMESPACE
/usr/lib64/R/library/callr/NEWS.md
/usr/lib64/R/library/callr/R/callr
/usr/lib64/R/library/callr/R/callr.rdb
/usr/lib64/R/library/callr/R/callr.rdx
/usr/lib64/R/library/callr/WORDLIST
/usr/lib64/R/library/callr/developer-notes.md
/usr/lib64/R/library/callr/help/AnIndex
/usr/lib64/R/library/callr/help/aliases.rds
/usr/lib64/R/library/callr/help/callr.rdb
/usr/lib64/R/library/callr/help/callr.rdx
/usr/lib64/R/library/callr/help/figures/bg-dark.svg
/usr/lib64/R/library/callr/help/figures/bg-methods-dark.svg
/usr/lib64/R/library/callr/help/figures/bg-methods.svg
/usr/lib64/R/library/callr/help/figures/bg.svg
/usr/lib64/R/library/callr/help/figures/error1-dark.svg
/usr/lib64/R/library/callr/help/figures/error1.svg
/usr/lib64/R/library/callr/help/figures/error2-2-dark.svg
/usr/lib64/R/library/callr/help/figures/error2-2.svg
/usr/lib64/R/library/callr/help/figures/io-2-dark.svg
/usr/lib64/R/library/callr/help/figures/io-2.svg
/usr/lib64/R/library/callr/help/figures/io-dark.svg
/usr/lib64/R/library/callr/help/figures/io.svg
/usr/lib64/R/library/callr/help/figures/packages-dark.svg
/usr/lib64/R/library/callr/help/figures/packages.svg
/usr/lib64/R/library/callr/help/figures/passargsfail-dark.svg
/usr/lib64/R/library/callr/help/figures/passargsfail.svg
/usr/lib64/R/library/callr/help/figures/passargsok-dark.svg
/usr/lib64/R/library/callr/help/figures/passargsok.svg
/usr/lib64/R/library/callr/help/figures/poll-2-dark.svg
/usr/lib64/R/library/callr/help/figures/poll-2.svg
/usr/lib64/R/library/callr/help/figures/poll-3-dark.svg
/usr/lib64/R/library/callr/help/figures/poll-3.svg
/usr/lib64/R/library/callr/help/figures/poll-4-dark.svg
/usr/lib64/R/library/callr/help/figures/poll-4.svg
/usr/lib64/R/library/callr/help/figures/poll-dark.svg
/usr/lib64/R/library/callr/help/figures/poll.svg
/usr/lib64/R/library/callr/help/figures/rcmd-dark.svg
/usr/lib64/R/library/callr/help/figures/rcmd.svg
/usr/lib64/R/library/callr/help/figures/rsession-4-dark.svg
/usr/lib64/R/library/callr/help/figures/rsession-4.svg
/usr/lib64/R/library/callr/help/figures/rsession-5-dark.svg
/usr/lib64/R/library/callr/help/figures/rsession-5.svg
/usr/lib64/R/library/callr/help/figures/rsession-dark.svg
/usr/lib64/R/library/callr/help/figures/rsession.svg
/usr/lib64/R/library/callr/help/figures/rsession2-2-dark.svg
/usr/lib64/R/library/callr/help/figures/rsession2-2.svg
/usr/lib64/R/library/callr/help/figures/rsession2-dark.svg
/usr/lib64/R/library/callr/help/figures/rsession2.svg
/usr/lib64/R/library/callr/help/figures/simple-dark.svg
/usr/lib64/R/library/callr/help/figures/simple.svg
/usr/lib64/R/library/callr/help/paths.rds
/usr/lib64/R/library/callr/html/00Index.html
/usr/lib64/R/library/callr/html/R.css
/usr/lib64/R/library/callr/tests/testthat.R
/usr/lib64/R/library/callr/tests/testthat/_snaps/error.md
/usr/lib64/R/library/callr/tests/testthat/fixtures/D1
/usr/lib64/R/library/callr/tests/testthat/fixtures/csomag/DESCRIPTION
/usr/lib64/R/library/callr/tests/testthat/fixtures/csomag/NAMESPACE
/usr/lib64/R/library/callr/tests/testthat/fixtures/csomag/R/libpath.R
/usr/lib64/R/library/callr/tests/testthat/fixtures/script.R
/usr/lib64/R/library/callr/tests/testthat/fixtures/script2.R
/usr/lib64/R/library/callr/tests/testthat/fixtures/simple.txt
/usr/lib64/R/library/callr/tests/testthat/helper.R
/usr/lib64/R/library/callr/tests/testthat/test-archs.R
/usr/lib64/R/library/callr/tests/testthat/test-bugs.R
/usr/lib64/R/library/callr/tests/testthat/test-callback.R
/usr/lib64/R/library/callr/tests/testthat/test-clean-subprocess.R
/usr/lib64/R/library/callr/tests/testthat/test-error.R
/usr/lib64/R/library/callr/tests/testthat/test-eval.R
/usr/lib64/R/library/callr/tests/testthat/test-function-env.R
/usr/lib64/R/library/callr/tests/testthat/test-hook.R
/usr/lib64/R/library/callr/tests/testthat/test-libpath.R
/usr/lib64/R/library/callr/tests/testthat/test-load-client.R
/usr/lib64/R/library/callr/tests/testthat/test-messages.R
/usr/lib64/R/library/callr/tests/testthat/test-options.R
/usr/lib64/R/library/callr/tests/testthat/test-package.R
/usr/lib64/R/library/callr/tests/testthat/test-presets.R
/usr/lib64/R/library/callr/tests/testthat/test-quit.R
/usr/lib64/R/library/callr/tests/testthat/test-r-bg.R
/usr/lib64/R/library/callr/tests/testthat/test-r-process.R
/usr/lib64/R/library/callr/tests/testthat/test-r-session-messages.R
/usr/lib64/R/library/callr/tests/testthat/test-r-session.R
/usr/lib64/R/library/callr/tests/testthat/test-rcmd-bg.R
/usr/lib64/R/library/callr/tests/testthat/test-rcmd-process.R
/usr/lib64/R/library/callr/tests/testthat/test-rcmd.R
/usr/lib64/R/library/callr/tests/testthat/test-rscript.R
/usr/lib64/R/library/callr/tests/testthat/test-spelling.R
/usr/lib64/R/library/callr/tests/testthat/test-timeout.R
/usr/lib64/R/library/callr/tests/testthat/test-utils.R
